### PR TITLE
SonarConfigurationFileParser tests fail on cygwin (Windows)

### LINKED ISSUE #1424: SonarConfigurationFileParser tests fail on Windows
Several SonarConfigurationFileParser tests fail on Windows because SonarConfigurationFileParser::parse() assumes lines in the property files only end with a new line.

### PR DESCRIPTION
**Pull request by BlairCooper**
Fixes #1424

Use preg_split ("/\r?\n/", $contents) instead of expand ("\n", $contents) to
account for files which use CRLF or LF (aka newline) as the line
termination character.

Previous failures on Windows:
[phpunit] Testsuite: SonarConfigurationFileParserTest
[phpunit] Tests run: 13, Warnings: 1, Failures: 7, Errors: 0, Incomplete: 0, Skipped: 0, Time elapsed: 0.37023 s
[phpunit] testPropertyWithColonAndWithoutWhitespace FAILED
[phpunit] Failed asserting that an array contains 'bar'.
[phpunit] testPropertyWithColonAndWithWhitespace FAILED
[phpunit] Failed asserting that an array contains 'bar'.
[phpunit] testPropertyWithEqualsSignAndWithoutWhitespace FAILED
[phpunit] Failed asserting that an array contains 'bar'.
[phpunit] testPropertyWithEqualsSignAndWithWhitespace FAILED
[phpunit] Failed asserting that an array contains 'bar'.
[phpunit] testPropertyHasMultiLineValue FAILED
[phpunit] Failed asserting that an array contains 'This is a multi-line comment.'.
[phpunit] testPropertyEndsWithABackSlash FAILED
[phpunit] Failed asserting that an array contains 'This is not a multi-line property, but ends with a backslash\'.
[phpunit] testPropertyHasMultiLineValueIntermediateLineIsEmpty FAILED
[phpunit] Failed asserting that an array contains 'This is a multi-line comment.'.

### CODE REVIEW

**Comment by siad007** [comment]
@BlairCooper thx for your contribution - would you mind to add a test for your assumption please.

**Review by siad007 — CHANGES_REQUESTED** [review]
Please add a test.

**Comment by siad007** [comment]
Hmm strange - how do you execute the test suite? I cannot reproduce it.
Also see https://ci.appveyor.com/project/mrook/phing/builds/36191699 where no test is failing.

File: classes/phing/tasks/ext/sonar/SonarConfigurationFileParser.php [hunk 1]
```diff
@@ -89,7 +89,7 @@ public function parse()
             throw new BuildException($message);
         }
 
-        $lines = explode("\n", $contents);
+        $lines = preg_split ("/\r?\n/", $contents);
```
Comment (siad007) [inline classes/phing/tasks/ext/sonar/SonarConfigurationFileParser.php:92]: https://travis-ci.com/github/phingofficial/phing/jobs/430758078

**Review by siad007 — CHANGES_REQUESTED** [review]

File: classes/phing/tasks/ext/sonar/SonarConfigurationFileParser.php (hunk 1 above)
Comment (BlairCooper) [reply classes/phing/tasks/ext/sonar/SonarConfigurationFileParser.php]: Added tests specifically for /r/n versus /n.

While I'm on Windows I do run the tests in a Git Bash terminal so that combination may be exposing the issue.

**Review by siad007 — APPROVED** [review]
I could reproduce on windows using cygwin.
