### PR TITLE
ComposerTask tests don't need Composer on the path

### LINKED ISSUE #1426: ComposerTask test failing if Composer isn't on the path
If Composer isn't on the path the testSetGetComposer method will fail.

Test should simulate composer on the path instead of requiring Composer be installed and on the path.

### PR DESCRIPTION
**Pull request by BlairCooper**
Fixes #1426

Split out testing SetComposer and GetComposer methods. Simulate Composer
existing on the path.

### CODE REVIEW

File: test/classes/phing/tasks/ext/ComposerTaskTest.php [hunk 1]
```diff
@@ -72,18 +72,63 @@ public function testSetGetPhp()
...
+
+        $testPath = PHING_TEST_BASE . '/etc/tasks/ext/composer';
+        $orgPath = getenv("PATH");
+
+        $pathSeparator = FileSystem::getFileSystem()->getPathSeparator();
+        putenv("PATH=$testPath$pathSeparator$orgPath");
+
+        $pathComposer = $o->getComposer();
+
+        putenv("PATH=$orgPath");
```
Comment (siad007) [inline test/classes/phing/tasks/ext/ComposerTaskTest.php:128]: AFAIK windows uses `Path` and not `PATH` 🤔 ?

Comment (BlairCooper) [reply test/classes/phing/tasks/ext/ComposerTaskTest.php:128]: Windows isn't case sensitive so Path, PATH, and pAtH would all work.

**Comment by siad007** [comment]
@BlairCooper https://github.com/phingofficial/phing/issues/1426#issuecomment-723648918
